### ISSUE TITLE
Invert Animation

### ISSUE THREAD

**Issue by offboard** [johakr/html5-slot-machine#1]
Hello, I'd like change the order spinning.
I change the file Reel.js for setting to spinning for down

from       { transform: `translateY(-${((Math.floor(this.factor) * 10) / (3 + Math.floor(this.factor) * 10)) * 100}%)`, filter: 'blur(0)' },

to       { transform: `translateY(${((Math.floor(this.factor) * 10) / (3 + Math.floor(this.factor) * 10)) * 100}%)`, filter: 'blur(0)' },

but the order spinning is not perfect.

**Comment by johakr** [comment]
Hi @offboard, thanks for your request. 

I introduced a config object with 89a62bf67adc29bd7da35aea290710eb01330c23. With `inverted` being the first configurable property. Setting `inverted` to `true` in `index.js` should lead to your desired behavior.

Best
