### ISSUE TITLE
Configuration of spin.

### ISSUE THREAD

**Issue by davidkern13** [johakr/html5-slot-machine#174]
Hello, possible to make the spin starting all columns together but the finish of each column will happen one after other in some delay, like in regular slots ?

Thanks!

**Comment by johakr** [comment]
Hey David, that should already be the case.

https://github.com/johakr/html5-slot-machine/assets/10597806/49c5d09d-676f-4fe1-b688-65dbc1225257

Can you provide some example of your desired effect?

**Comment by davidkern13** [comment]
Hello Johannes, thanks for reply.

I am try to explain, first is when the spin starting the first column is finished first but the last column is spinning match more time and spins. possible to make each column starting together then each column will finished one after another for example follow steps of animation -> 

column 1: 3.1s of spin
column 1: 3.2s of spin
column 1: 3.3s of spin
column 1: 3.4s of spin
column 1: 3.5s of spin

like in this video but its based on react native ->
https://www.youtube.com/watch?v=xAh3iHehkWU&t=2179s&ab_channel=TamasSzikszai

Thanks!
