### ISSUE TITLE
Failed to load resource

### ISSUE THREAD

**Issue by akmalelias** [johakr/html5-slot-machine#27]
When fresh npm start, hit this issue in browser. Same goes to the demo site.

Can help to clarify what is missing?

Error message:
Failed to load resource: the server responded with a status of 404 () [object%20Module]:1

**Comment by johakr** [comment]
HI @akmalelias, thank you for raising this issue. 👍  

Fixed with 3e05a7fa114fa8492c74760a1c14240cf6dff04f
