### ISSUE TITLE
Feature Request: On Stop Event

### ISSUE THREAD

**Issue by erwinyusrizal** [johakr/html5-slot-machine#96]
Hi it would be great if there is a onStop event with the Symbol pattern (array) as callback value.

Thank you

**Comment by johakr** [comment]
Hi @erwinyusrizal, `onSpinStart` and `onSpinEnd` events are implemented with https://github.com/johakr/html5-slot-machine/commit/5e44c65cfde2deed01cb0f940bee319f332459b0.

**Comment by erwinyusrizal** [comment]
Cool, Thank you @johakr

**Comment by erwinyusrizal** [comment]
![image](https://user-image@johakr ithubusercontent.com/3752374/151710390-5903d69d-dce6-4533-b7b3-2957bff6b108.png)

@johakr I tried the demo, but why onSpinStart and onSpinEnd array return similar value? shouldn't it be different?

Thanks
